/* Automatically generated by './build/bin/build-entry.js' */

var BaseFlexGrid = require('../packages/base-flex-grid/index.js').default;
var ActionFlexGrid = require('../packages/action-flex-grid/index.js').default;
var Chart = require('../packages/chart/index.js').default;
var ChartMini = require('../packages/chart-mini/index.js').default;
var GridConfig = require('../packages/grid-config/index.js').default;
var GridDialog = require('../packages/grid-dialog/index.js').default;
var GridModule = require('../packages/grid-module/index.js').default;
var ImgViewer = require('../packages/img-viewer/index.js').default;
var Dialog = require('../packages/dialog/index.js').default;
var DialogMini = require('../packages/dialog-mini/index.js').default;
var Input = require('../packages/input/index.js').default;
var Lists = require('../packages/lists/index.js').default;
var Button = require('../packages/button/index.js').default;
var ButtonMenu = require('../packages/button-menu/index.js').default;
var Upload = require('../packages/upload/index.js').default;
var Tree = require('../packages/tree/index.js').default;
var FloatList = require('../packages/float-list/index.js').default;
var Accordion = require('../packages/accordion/index.js').default;
var Step = require('../packages/step/index.js').default;
var Steps = require('../packages/steps/index.js').default;
var Transition = require('../packages/transition/index.js').default;
var Cart = require('../packages/cart/index.js').default;
var CartMenu = require('../packages/cart-menu/index.js').default;
var LinkAll = require('../packages/link-all/index.js').default;
var Scrollbar = require('../packages/scrollbar/index.js').default;
var BackTop = require('../packages/back-top/index.js').default;
var CellRender = require('../packages/cell-render/index.js').default;
var Switch = require('../packages/switch/index.js').default;
var Carousel = require('../packages/carousel/index.js').default;
var CarouselItem = require('../packages/carousel-item/index.js').default;
var Multiples = require('../packages/multiples/index.js').default;
var Multiple = require('../packages/multiple/index.js').default;
var Spa = require('../packages/spa/index.js').default;
var LeftRight = require('../packages/left-right/index.js').default;
var TopBottom = require('../packages/top-bottom/index.js').default;

const components = [
  BaseFlexGrid,
  ActionFlexGrid,
  Chart,
  ChartMini,
  GridConfig,
  GridDialog,
  GridModule,
  ImgViewer,
  Dialog,
  DialogMini,
  Input,
  Lists,
  Button,
  ButtonMenu,
  Upload,
  Tree,
  FloatList,
  Accordion,
  Step,
  Steps,
  Transition,
  Cart,
  CartMenu,
  LinkAll,
  Scrollbar,
  BackTop,
  CellRender,
  Switch,
  Carousel,
  CarouselItem,
  Multiples,
  Multiple,
  Spa,
  LeftRight,
  TopBottom
];

const install = function(Vue, opts = {}) {
  components.map(component => {
    Vue.component(component.name, component);
  });


  const ELEMENT = {};
  ELEMENT.size = opts.size || '';
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

module.exports = {
  version: '2.1.47',
  install,
  BaseFlexGrid,
  ActionFlexGrid,
  Chart,
  ChartMini,
  GridConfig,
  GridDialog,
  GridModule,
  ImgViewer,
  Dialog,
  DialogMini,
  Input,
  Lists,
  Button,
  ButtonMenu,
  Upload,
  Tree,
  FloatList,
  Accordion,
  Step,
  Steps,
  Transition,
  Cart,
  CartMenu,
  LinkAll,
  Scrollbar,
  BackTop,
  CellRender,
  Switch,
  Carousel,
  CarouselItem,
  Multiples,
  Multiple,
  Spa,
  LeftRight,
  TopBottom
};

module.exports.default = module.exports;
